// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: createOrder.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createOrder = `-- name: CreateOrder :one

INSERT INTO orders(
    id,
    created_at,
    updated_at,
    user_id,
    recipe_id,
    status
)
VALUES(
    $1,
    NOW(),
    NOW(),
    $2,
    $3,
    'pending'::order_status
)

RETURNING id, created_at, user_id, recipe_id, status, started_at, completed_at, error_message
`

type CreateOrderParams struct {
	ID       uuid.UUID
	UserID   uuid.NullUUID
	RecipeID uuid.NullUUID
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, createOrder, arg.ID, arg.UserID, arg.RecipeID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UserID,
		&i.RecipeID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
	)
	return i, err
}
