// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: createCocktailRecipe.sql

package database

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createCocktailRecipe = `-- name: CreateCocktailRecipe :one
INSERT INTO cocktail_recipes(
    id,
    created_at,
    updated_at,
    name,
    ingredients,
    build
)
VALUES(
    $1,
    NOW(),
    NOW(),
    $2,
    $3,
    $4
)

RETURNING id, created_at, updated_at, name, ingredients, build
`

type CreateCocktailRecipeParams struct {
	ID          uuid.UUID
	Name        string
	Ingredients json.RawMessage
	Build       BuildType
}

func (q *Queries) CreateCocktailRecipe(ctx context.Context, arg CreateCocktailRecipeParams) (CocktailRecipe, error) {
	row := q.db.QueryRowContext(ctx, createCocktailRecipe,
		arg.ID,
		arg.Name,
		arg.Ingredients,
		arg.Build,
	)
	var i CocktailRecipe
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Ingredients,
		&i.Build,
	)
	return i, err
}
