// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: createUser.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one

INSERT INTO users(
    id,
    created_at,
    updated_at,
    username,
    email,
    role,
    hashed_password
    )
VALUES(
    $1,
    NOW(),
    NOW(),
    $2,
    $3,
    $4,
    $5
)
RETURNING id, created_at, updated_at, username, email, role, hashed_password
`

type CreateUserParams struct {
	ID             uuid.UUID
	Username       string
	Email          string
	Role           UserRole
	HashedPassword string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.Role,
		arg.HashedPassword,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.HashedPassword,
	)
	return i, err
}
