// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: getAllCocktailRecipes.sql

package database

import (
	"context"
)

const getAllRecipes = `-- name: GetAllRecipes :many

SELECT id, created_at, updated_at, name, ingredients, build FROM cocktail_recipes
ORDER BY build
`

func (q *Queries) GetAllRecipes(ctx context.Context) ([]CocktailRecipe, error) {
	rows, err := q.db.QueryContext(ctx, getAllRecipes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CocktailRecipe
	for rows.Next() {
		var i CocktailRecipe
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Ingredients,
			&i.Build,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
