// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: getOrderByID.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getOrderByID = `-- name: GetOrderByID :one

SELECT id, created_at, user_id, recipe_id, status, started_at, completed_at, error_message FROM orders
WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UserID,
		&i.RecipeID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
	)
	return i, err
}
