// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: getRecipeByName.sql

package database

import (
	"context"
)

const getRecipeByName = `-- name: GetRecipeByName :one

SELECT id, created_at, updated_at, name, ingredients, build FROM cocktail_recipes
WHERE name = $1
`

func (q *Queries) GetRecipeByName(ctx context.Context, name string) (CocktailRecipe, error) {
	row := q.db.QueryRowContext(ctx, getRecipeByName, name)
	var i CocktailRecipe
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Ingredients,
		&i.Build,
	)
	return i, err
}
