// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type BuildType string

const (
	BuildTypeStirred BuildType = "stirred"
	BuildTypeShaken  BuildType = "shaken"
	BuildTypeSour    BuildType = "sour"
	BuildTypeCollins BuildType = "collins"
)

func (e *BuildType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BuildType(s)
	case string:
		*e = BuildType(s)
	default:
		return fmt.Errorf("unsupported scan type for BuildType: %T", src)
	}
	return nil
}

type NullBuildType struct {
	BuildType BuildType
	Valid     bool // Valid is true if BuildType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBuildType) Scan(value interface{}) error {
	if value == nil {
		ns.BuildType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BuildType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBuildType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BuildType), nil
}

type Status string

const (
	StatusPending    Status = "pending"
	StatusInProgress Status = "in_progress"
	StatusComplete   Status = "complete"
	StatusFailed     Status = "failed"
)

func (e *Status) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Status(s)
	case string:
		*e = Status(s)
	default:
		return fmt.Errorf("unsupported scan type for Status: %T", src)
	}
	return nil
}

type NullStatus struct {
	Status Status
	Valid  bool // Valid is true if Status is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStatus) Scan(value interface{}) error {
	if value == nil {
		ns.Status, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Status.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Status), nil
}

type UserRole string

const (
	UserRoleCustomer UserRole = "customer"
	UserRoleEmployee UserRole = "employee"
	UserRoleAdmin    UserRole = "admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type CocktailRecipe struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Name        string
	Ingredients json.RawMessage
	Build       BuildType
}

type Order struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	UserID       uuid.UUID
	RecipeID     uuid.UUID
	Status       Status
	StartedAt    sql.NullTime
	CompletedAt  sql.NullTime
	ErrorMessage sql.NullString
}

type User struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Username       string
	Email          string
	Role           UserRole
	HashedPassword string
}
