// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: resetDatabase.sql

package database

import (
	"context"
)

const resetDatabase = `-- name: ResetDatabase :exec

TRUNCATE TABLE orders, cocktail_recipes, users RESTART IDENTITY CASCADE
`

func (q *Queries) ResetDatabase(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetDatabase)
	return err
}
