// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: updateUserRole.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updateUserRole = `-- name: UpdateUserRole :exec

UPDATE users
SET
    role = $1,
    updated_at = NOW()
WHERE id = $2
`

type UpdateUserRoleParams struct {
	Role UserRole
	ID   uuid.UUID
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.ExecContext(ctx, updateUserRole, arg.Role, arg.ID)
	return err
}
