// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: updateOrderStatus.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updateOrderStatus = `-- name: UpdateOrderStatus :exec

UPDATE orders
SET
    status = $1,
    updated_at = NOW()
WHERE id = $2
`

type UpdateOrderStatusParams struct {
	Status Status
	ID     uuid.UUID
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateOrderStatus, arg.Status, arg.ID)
	return err
}
