FROM golang:1.22-alpine AS build

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o consumer ./cmd/consumer

FROM alpine:3.19
WORKDIR /app
COPY --from=build /app/consumer .

CMD ["./consumer"]
